- name: Ensure zoxide is in the PATH
  ansible.builtin.lineinfile:
    path: /home/{{ ansible_user }}/.zshrc
    line: eval "$(zoxide init zsh)"
  ignore_errors: true

  become: true

- name: create Alias to Zoxide as cd
  ansible.builtin.lineinfile:
    path: /home/{{ ansible_user }}/.zshrc
    line: alias cd='z'
  ignore_errors: true
  become: true
