- name: install api client tools
  community.general.flatpak:
    name:
      - es.danirod.Cartero
      - com.getpostman.Postman
      - com.usebruno.Bruno
      - rest.insomnia.Insomnia
    state: present
    method: user
