- import_tasks: zoxide.yaml
- import_tasks: lazy-packages.yaml
- import_tasks: fzf.yaml
- import_tasks: fnm.yaml
- import_tasks: uv.yaml
- import_tasks: docker.yaml
- import_tasks: open_code.yaml
#faltante ZSH + plugins
