- name: Install UV Package Manager
  ansible.builtin.shell: |
    curl -LsSf https://astral.sh/uv/install.sh | less
  args:
    executable: /bin/bash
    creates: /home/{{ ansible_user }}/.local/bin/uv
  become: true
  environment:
    HOME: "/home/{{ ansible_user }}"
    USER: "{{ ansible_user }}"
