- name: Install zoxide
  ansible.builtin.shell: |
    curl -sSfL https://raw.githubusercontent.com/ajeetdsouza/zoxide/main/install.sh | sh || true
  args:
    executable: /bin/bash
    creates: /home/{{ ansible_user }}/.local/bin/zoxide
  environment:
    HOME: "/home/{{ ansible_user }}"
    USER: "{{ ansible_user }}"
  ignore_errors: true
  become: true
