- name: install zsh
  ansible.builtin.apt:
    name: zsh
    state: present
    update_cache: yes
  become: true

- name: install oh-my-zsh
  ansible.builtin.shell: |
    sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
  args:
    executable: /bin/bash
    creates: /home/{{ ansible_user }}/.oh-my-zsh
  become: true
