- name: "Install core packages"
  hosts: local
  gather_facts: false

  roles:
    - software_development_packages
    - software_development_packages/configuration

- import_playbook: install_programming_languages.yaml
